### ISSUE TITLE
Fails to run if `bash` isn't at `/usr/local/bin/bash`

### ISSUE THREAD

**Issue by jonluca** [EasyG0ing1/MacIcns#1]
<img width="1257" alt="capture 2023-01-30 at 12 29 10 PM" src="https://user-images.githubusercontent.com/13029040/215550318-4bf941a3-9504-45ff-9f0e-17f4ea2ba06f.png">

Creating a symlink there makes it work `sudo ln -s /opt/homebrew/bin/bash /usr/local/bin/bash`

but it would be nice if this tried to find your bash inside $PATH instead of relying on a hardcoded one. 

Thanks for the app btw!

**Comment by EasyG0ing1** [comment]
@jonluca OK, I'll work that in and post an update.

**Comment by EasyG0ing1** [comment]
@jonluca 
Fixed in [release 1.0.1](https://github.com/EasyG0ing1/MacIcns/releases/tag/1.0.1)

Would you test it please and let me know if it works for you?

**Comment by EasyG0ing1** [comment]
@jonluca 

Pushed [another update](https://github.com/EasyG0ing1/MacIcns/releases/tag/1.1.0) with an added feature.

**Comment by EasyG0ing1** [comment]
This has been fixed, download the [latest version](https://github.com/EasyG0ing1/MacIcns/releases/latest).
